---
title: "Neonatal Outcomes AI Prediction using Multimodal Trajectory Database"
author: "Herdiantri Sufriyana, Chao-Ching Huang, Emily Chia-Yu Su"
date: "2024-09-10"
output: html_document
---

# Programming environment

```{r Set random seed, include=FALSE, paged.print=FALSE}
seed <- 2024-09-10
```

```{r Load R packages, include=FALSE}
library(tidyverse)
library(knitr)
library(kableExtra)
library(ggpubr)
library(readxl)
library(broom)
library(MASS)
select <- dplyr::select
library(igraph)
library(ggnetwork)
library(brms)
library(broom.mixed)
library(pbapply)
library(mice)
filter <- dplyr::filter
cbind <- base::cbind
rbind <- base::rbind
library(parallel)
library(doParallel)
```

```{r Load custom functions, include=FALSE}
lapply(list.files("R/", pattern = "-function.R", full.names = TRUE), source)
```

```{r Set theme, include=FALSE}
dslabs::ds_theme_set()
kable_format <- "html"
```

# Load raw data

```{r List raw data paths, include=FALSE}
paths_old_name <-
  list.files(
    "inst/extdata/2011-202312_GA_22-30_838"
    , pattern = "\\.xlsx$"
    , full.names = TRUE
  )
```

```{r Write raw data path old names, eval=FALSE, include=FALSE}
data.frame(name = NA, path = paths_old_name)  |>
  write_csv("inst/extdata/paths_old_name.csv")
```

```{r Read raw data path new names, include=FALSE}
paths_new_name <-
  read_csv("inst/extdata/paths_new_name.csv", show_col_types = FALSE)
```

```{r table-1, echo=FALSE}
paths_new_name |>
  kable(
    caption = "Table 1. Raw data names and paths."
    , format = kable_format
  ) |>
  kable_classic() |>
  column_spec(1:2, extra_css = "vertical-align:top;")
```

```{r Read raw data, include=FALSE}
raw_data <-
  paths_new_name$path |>
  `names<-`(paths_new_name$name) |>
  lapply(read_xlsx, sheet = 1)
```

# Data preprocessing

## Data cleaning

```{r List raw data colnames, include=FALSE}
raw_data_old_colname <-
  raw_data |>
  imap(
    ~ data.frame(
        table = .y
        , old_colname = colnames(.x)
        , new_colname = NA
      )
  ) |>
  reduce(rbind)
```

```{r Write raw data old colnames, eval=FALSE, include=FALSE}
raw_data_old_colname |>
  write_csv("inst/extdata/raw_data_old_colname.csv")
```

```{r Read raw data new colnames, include=FALSE}
raw_data_new_colname <-
  read_csv("inst/extdata/raw_data_new_colname.csv", show_col_types = FALSE)
```

```{r table-2, echo=FALSE}
raw_data_new_colname |>
  mutate(table = ifelse(duplicated(table), "", table)) |>
  kable(
    caption = "Table 2. Raw data old and new column names."
    , format = kable_format
  ) |>
  kable_classic() |>
  column_spec(1:2, extra_css = "vertical-align:top;")
```

```{r Modify column names, include=FALSE}
raw_data1 <-
  raw_data |>
  imap(
    ~ .x |>
      `colnames<-`(
        data.frame(table = .y, old_colname = colnames(.x)) |>
          left_join(raw_data_new_colname, by = join_by(table, old_colname)) |>
          mutate(
            new_colname =
              ifelse(is.na(new_colname), old_colname, new_colname)
          ) |>
          pull(new_colname)
      )
  )
```

```{r Join raw data tables accordingly, include=FALSE}
raw_data2 <-
  raw_data1[!str_detect(names(raw_data1), "42d$|6w$")] |>
  reduce(\(x, y) left_join(x, y, by = join_by(id))) |>
  right_join(
    raw_data1[str_detect(names(raw_data1), "6w$")] |>
      reduce(\(x, y) left_join(x, y, by = join_by(id, t_wk)))
    , by = join_by(id, ga_wk)
  ) |>
  right_join(
    raw_data1[str_detect(names(raw_data1), "42d$")] |>
      reduce(\(x, y) left_join(x, y, by = join_by(id, t_day))) |>
      mutate(t_wk = ceiling(t_day / 7))
    , by = join_by(id, t_wk)
  ) |>
  select(-t_wk) |>
  select(id, t = t_day, everything())
```

```{r List raw data variable-types, include=FALSE}
variable_old_type <-
  data.frame(
    variable = colnames(raw_data2)
    , old_type = sapply(raw_data2, class)
    , new_type = NA
  )
```

```{r Write old variable-types, eval=FALSE, include=FALSE}
variable_old_type |>
  write_csv("inst/extdata/variable_old_type.csv")
```

```{r Read new variable-types, include=FALSE}
variable_new_type <-
  read_csv("inst/extdata/variable_new_type.csv", show_col_types = FALSE)
```

```{r table-3, echo=FALSE}
variable_new_type |>
  kable(
    caption = "Table 3. Raw data old and new variable types."
    , format = kable_format
  ) |>
  kable_classic() |>
  column_spec(1:2, extra_css = "vertical-align:top;")
```

```{r Modify variable-types, include=FALSE}
raw_data3 <-
  raw_data2 |>
  imap(
    ~ data.frame(
        value =
          ifelse(
            filter(variable_new_type, variable == .y)$new_type != "numeric"
            ,as.character
            ,as.numeric
          )(.x)
      ) |>
      `colnames<-`(.y)
  ) |>
  reduce(cbind)

raw_data3 <-
  unique(variable_new_type$new_type) |>
  `names<-`(unique(variable_new_type$new_type)) |>
  imap(
    ~ raw_data3 |>
      select_at(filter(variable_new_type, new_type == .x)$variable)
  )
```

```{r List raw data categories, include=FALSE}
raw_data_old_cat <-
  raw_data3$factor |>
  lapply(unique) |>
  lapply(sort) |>
  imap(~ data.frame(colname = .y, old_cat = .x, new_cat = NA)) |>
  reduce(rbind) |>
  mutate_at("colname", \(x) factor(x, unique(x)))
```

```{r Write raw data old categories, eval=FALSE, include=FALSE}
raw_data_old_cat |>
  write_csv("inst/extdata/raw_data_old_cat.csv")
```

```{r Read raw data new categories, include=FALSE}
raw_data_new_cat <-
  read_csv("inst/extdata/raw_data_new_cat.csv", show_col_types = FALSE) |>
  mutate_at("old_cat", as.character)
```

```{r table-4, echo=FALSE}
raw_data_new_cat |>
  kable(
    caption = "Table 4. Raw data old and new categories."
    , format = kable_format
  ) |>
  kable_classic() |>
  column_spec(1:2, extra_css = "vertical-align:top;")
```

```{r Modify categories, include=FALSE}
raw_data4 <- raw_data3

raw_data4$factor <-
  raw_data4$factor |>
  mutate(seq = seq(n())) |>
  gather(colname, old_cat, -seq) |>
  mutate_at("colname", \(x) factor(x, unique(x))) |>
  left_join(raw_data_new_cat, by = join_by(colname, old_cat)) |>
  select(-old_cat) |>
  spread(colname, new_cat) |>
  arrange(seq) |>
  select(-seq) |>
  mutate_all(as.factor)

raw_data4 <-
  raw_data4 |>
  reduce(cbind) |>
  select_at(colnames(raw_data2))
```

```{r table-5, eval=FALSE, include=FALSE}
raw_data4 |>
  select(id, survive, death_age) |>
  unique() |>
  mutate(ms_death_age = is.na(death_age)) |>
  group_by(survive, ms_death_age) |>
  summarize(n = n(), .groups = "drop") |>
  kable(
    caption = "Table 5. Consistency check - survival and age of death."
    , format = kable_format
  ) |>
  kable_classic() |>
  column_spec(1:3, extra_css = "vertical-align:top;")
```

```{r table-6, eval=FALSE, include=FALSE}
raw_data4 |>
  select_at(colnames(raw_data1$outcomes)) |>
  unique() |>
  select(-id, -survive) |>
  mutate_all(\(x) ifelse(is.na(x), "missing", "non-missing")) |>
  rename_all(\(x) paste0("ms_", x)) |>
  gather(variable, value, -ms_death_age) |>
  group_by(ms_death_age, variable, value) |>
  summarize(n = n(), .groups = "drop") |>
  spread(value, n, fill = 0) |>
  mutate(ms_death_age = ifelse(duplicated(ms_death_age), "", ms_death_age)) |>
  kable(
    caption = "Table 6. Consistency check - other outcomes and age of death."
    , format = kable_format
  ) |>
  kable_classic() |>
  column_spec(1:3, extra_css = "vertical-align:top;")
```

```{r table-7, eval=FALSE, include=FALSE}
list(
    ceiled = mutate(raw_data4, t_death_age = ceiling(death_age))
    , rounded_plus1 = mutate(raw_data4, t_death_age = round(death_age) + 1)
    , floored_plus1 = mutate(raw_data4, t_death_age = floor(death_age) + 1)
  ) |>
  imap(
    ~ .x |>
      filter(survive == levels(survive)[1]) |>
      select_if(
        !colnames(.x)
        %in% c(
          colnames(select(raw_data1$demographic_surfactant_growth, -id))
          , colnames(select(raw_data1$outcomes, -id, -death_age))
          , colnames(select(raw_data1$morbidities_42d, -id))
        )
      ) |>
      mutate(
        t_wk = ceiling(t / 7)
        , t_wk_death_age = ceiling(t_death_age / 7)
      ) |>
      mutate(
        t_alive = ifelse(t <= t_death_age, "1-yes", "0-no")
        , t_wk_alive = ifelse(t_wk <= t_wk_death_age, "1-yes", "0-no")
      ) |>
      select(-death_age, -t_death_age, -t_wk_death_age) |>
      select(id, t, t_wk, t_alive, t_wk_alive, everything()) |>
      mutate_at(
        vars(-id, -t, -t_wk, -t_alive, -t_wk_alive)
        , \(x) ifelse(is.na(x), "missing", "non-missing")
      ) |>
      gather(variable, value, -id, -t, -t_wk, -t_alive, -t_wk_alive) |>
      mutate(
        t =
          ifelse(
            variable
            %in% unlist(
              lapply(raw_data1[str_detect(names(raw_data1), "6w$")], colnames)
            )
            , t_wk
            , t
          ) |>
          factor()
        , t_alive =
          ifelse(
            variable
            %in% unlist(
              lapply(raw_data1[str_detect(names(raw_data1), "6w$")], colnames)
            )
            , t_wk_alive
            , t_alive
          ) |>
          factor()
      ) |>
      select(-t_wk, -t_wk_alive) |>
      unique() |>
      mutate(
        variable = paste0("ms_", variable)
        ,variable = factor(variable, unique(variable))
      ) |>
      mutate(t_death_age_def = .y)
  ) |>
  reduce(rbind) |>
  mutate(t_death_age_def = factor(t_death_age_def, unique(t_death_age_def))) |>
  group_by(t_death_age_def, t_alive, variable, value) |>
  summarize(n = n(), .groups = "drop") |>
  spread(value, n, fill = 0) |>
  mutate(
    t_alive = as.character(t_alive)
    , t_alive =
      ifelse(
        duplicated(paste0(t_death_age_def, t_alive))
        , ""
        , t_alive
      )
    , t_death_age_def = as.character(t_death_age_def)
    , t_death_age_def = ifelse(duplicated(t_death_age_def), "", t_death_age_def)
  ) |>
  kable(
    caption =
      "Table 7. Consistency check - time-dependent variables and age of death."
    , format = kable_format
  ) |>
  kable_classic() |>
  column_spec(1:5, extra_css = "vertical-align:top;")
```

```{r Filter data up to death age if not survive, include=FALSE}
raw_data5 <-
  raw_data4 |>
  filter(is.na(death_age) | t <= (round(death_age) + 1))
```

```{r Finalize cleaned data, include=FALSE}
cleaned_data <- raw_data5
```

## Data partition

```{r Split data for each GA (week), include=FALSE}
# Determine whole set
whole_set <-
  cleaned_data |>
  select(id, ga_wk) |>
  unique()

# Split data by GA (week)
whole_id <-
  whole_set |>
  pull(ga_wk) |>
  unique() |>
  sort() |>
  lapply(\(x) filter(whole_set, ga_wk == x)$id)


# GA-wise partitioning
train_id <- list()
val_id <- list()
test_id <- list()

for(i in seq(length(whole_id))){
  set.seed(seed)
  
  test_id[[i]] <-
    whole_id[[i]] |>
    sample(size = round(0.2 * length(whole_id[[i]])), replace = FALSE)
  
  train_id[[i]] <- setdiff(whole_id[[i]], test_id[[i]])
  
  set.seed(seed)
  
  val_id[[i]] <-
    train_id[[i]] |>
    sample(size = round(0.2 * length(train_id[[i]])), replace = FALSE)
  
  train_id[[i]] <- setdiff(train_id[[i]], val_id[[i]])
}

whole_id <- reduce(whole_id, c)
train_id <- reduce(train_id, c)
val_id <- reduce(val_id, c)
test_id <- reduce(test_id, c)
```

```{r figure-1, include=FALSE}
whole_set |>
    mutate(
    set =
      case_when(
        id %in% train_id ~ "training"
        ,id %in% val_id ~ "validation"
        ,id %in% test_id ~ "test"
      ) |>
      factor(c("training", "validation", "test"))
  ) |>
  ggplot(aes(ga_wk)) +
  geom_histogram(binwidth = 1, color = "white") +
  facet_grid(set ~ ., scales = "free_y") +
  scale_x_continuous(breaks = seq(22, 30)) +
  theme(strip.text.y = element_text(angle = 0))
```

Figure 1. GA (week) distribution for each partition. GA, gestational week.

```{r Finalize inference data, include=FALSE}
infer_data <-
  cleaned_data |>
  filter(id %in% train_id)
```

## Numerical data transformation

```{r Separate categorical and numerical variables, include=FALSE}
cat_data <-
  infer_data |>
  select_if(!sapply(infer_data, is.numeric))

num_data <-
  infer_data |>
  select_if(sapply(infer_data, is.numeric))
```

```{r Normal QQ plots of numeric variables, include=FALSE}
normal_qq <-
  num_data |>
  imap(~ qq_plot_outlier(.x, .y))

normal_qq <-
  normal_qq |>
  length() |>
  seq() |>
  split(LETTERS[1:3]) |>
  data.frame() |>
  pmap(
    \(A, B, C)
    ggarrange(
      normal_qq[[A]]
      , normal_qq[[B]]
      , normal_qq[[C]]
      , ncol = 3
    )
  )

normal_qq <-
  ggarrange(
    normal_qq[[1]]
    , normal_qq[[2]]
    , normal_qq[[3]]
    , normal_qq[[4]]
    , normal_qq[[5]]
    , normal_qq[[6]]
    , normal_qq[[7]]
    , normal_qq[[8]]
    , normal_qq[[9]]
    , normal_qq[[10]]
    , ncol = 1
    , nrow = 10
  )
```

```{r figure-2, echo=FALSE, fig.height=50, fig.width=15}
normal_qq
```

Figure 2. QQ plot of numerical variables. QQ, quantile-to-quantile.

```{r Determine normality by QQ plot, include=FALSE}
var_num_normal_qq <-
  c("t"
    , "maternal_age"
    , "gravida"
    , "bbw_g"
    , "ga_wk"
    , "as1"
    , "as5"
    , "resuscitation_at_birth"
    , "steroid_antenatal"
    , "surfactant"
    , "bbw_z"
    , "bhc_z"
    , "resp_supp_agg_cum_day_qw"
    , "fio2_cum_day_qw"
    , "fio2_cum_level_qw"
    , "resp_supp_agg_cum_day_pct"
    , "fio2_cum_day_pct"
    , "fio2_cum_level_pct"
    , "steroid_postnatal"
    , "inotropic"
    , "blood_volume"
    , "transfusion"
    , "blood_culture"
    , "plt"
    , "wbc"
    , "feeding"
    , "nec"
    , "aki"
  )
```

```{r Numerical variables with normal distribution by QQ plots, echo=FALSE}
var_num_normal_qq |>
  paste0(collapse=', ') |>
  cat()
```

```{r Normality test of numerical variables, include=FALSE}
normal_test <-
  num_data |>
  select_if(!names(num_data) %in% var_num_normal_qq) |>
  lapply(
    \(x)
    suppressWarnings(
        ks.test(
          x
          , y = "pnorm"
          , mean = mean(x, na.rm = TRUE)
          , sd = sd(x, na.rm = TRUE)
        )
      )
  ) |>
  lapply(tidy) |>
  imap(~ mutate(.x, variable = .y)) |>
  lapply(select, variable, everything()) |>
  reduce(rbind)
```

```{r table-8, echo=FALSE}
normal_test |>
  select(-method) |>
  mutate_at("statistic", round, 3) |>
  arrange(p.value) |>
  mutate(variable = paste0(variable, ifelse(p.value<=0.05,"*",""))) |>
  mutate(p.value = ifelse(p.value<0.001, "<0.001", round(p.value,3))) |>
  kable(
    caption = "Table 8. Normality test."
    , format = kable_format
  ) |>
  footnote("*, p-value <=0.05, Shapiro-Wilk normality test.") |>
  kable_classic() |>
  column_spec(1:4, extra_css = "vertical-align:top;")
```

```{r Determine num variables that are not normally distributed, include=FALSE}
var_num_non_normal <-
  normal_test |>
  filter(p.value <= 0.05) |>
  pull(variable)
```

```{r Numerical variables that are not normally distributed, echo=FALSE}
var_num_non_normal |>
  paste0(collapse=', ') |>
  cat()
```

```{r Non-normal mumerical variables with 0, include=FALSE}
var_num_non_normal_with_zero <-
  num_data |>
  select_at(var_num_non_normal) |>
  lapply(\(x) x[!duplicated(x)]) |>
  lapply(\(x) x[!is.na(x)]) |>
  sapply(\(x) any(x==0)) |>
  which() |>
  names()
```

```{r Non-normal mumerical variables with <0, include=FALSE}
var_num_non_normal_with_neg <-
  num_data |>
  select_at(var_num_non_normal) |>
  lapply(\(x) x[!duplicated(x)]) |>
  lapply(\(x) x[!is.na(x)]) |>
  sapply(\(x) any(x<0)) |>
  which() |>
  names()
```

```{r Non-normal mumerical variables infinited exp, include=FALSE}
var_num_non_normal_with_inf_exp <-
  num_data |>
  select_at(var_num_non_normal) |>
  lapply(\(x) x[!duplicated(x)]) |>
  lapply(\(x) x[!is.na(x)]) |>
  sapply(\(x) any(is.infinite(exp(x)))) |>
  which() |>
  names()
```

```{r Determine choices for a transformation technique, include=FALSE}
trans_choice <-
  data.frame(variable = var_num_non_normal) |>
  mutate(
    log =
      ifelse(
        variable%in%var_num_non_normal_with_zero
        | variable%in%var_num_non_normal_with_neg
        , 0
        , 1
      )
    ,sqrt =
      ifelse(
        variable%in%var_num_non_normal_with_neg
        , 0
        , 1
      )
    ,inv =
      ifelse(
        variable%in%var_num_non_normal_with_zero
        | variable%in%var_num_non_normal_with_neg
        , 0
        , 1
      )
    ,log2 =
      ifelse(
        variable%in%var_num_non_normal_with_zero
        | variable%in%var_num_non_normal_with_neg
        , 0
        , 1
      )
    ,exp =
      ifelse(
        variable%in%var_num_non_normal_with_inf_exp
        , 0
        , 1
      )
    ,asinh = 1
    ,bct =
      ifelse(
        variable%in%var_num_non_normal_with_zero
        | variable%in%var_num_non_normal_with_neg
        , 0
        , 1
      )
  )
```

```{r Choices for a transformation technique, echo=FALSE}
trans_choice |>
  colnames() |>
  setdiff("variable") |>
  paste0(collapse=', ') |>
  cat()
```

```{r Simple transformations, include=FALSE}
simple_trans <-
  trans_choice |>
  gather(func, do, -variable) |>
  filter(do == 1) |>
  select(-do) |>
  filter(!func %in% c("bct"))

simple_trans <-
  simple_trans |>
  pull(func) |>
  unique() |>
  lapply(
    \(x)
    simple_trans |>
      filter(func == x) |>
      pull(variable) |>
      lapply(
        \(y)
        list(
            log = log
            , sqrt = sqrt
            , inv = \(x) 1/x
            , log2 = log2
            , exp = exp
            , asinh = asinh
          )[[x]](num_data[[y]]) |>
          as.data.frame() |>
          `colnames<-`(y)
      ) |>
       `names<-`(
         simple_trans |>
          filter(func == x) |>
          pull(variable)
       )
  ) |>
  `names<-`(unique(simple_trans$func))
```

```{r Box-Cox transformation (BCT), include=FALSE}
bc_trans <-
  trans_choice |>
  gather(func, do, -variable) |>
  filter(do == 1) |>
  select(-do) |>
  filter(func %in% c("bct")) |>
  pull(variable)

bc_trans <-
  bc_trans |>
  `names<-`(as.character(bc_trans)) |>
  as.list()

for(i in names(bc_trans)){
  bc_trans[[i]]=
    boxcox(
      lm(num_data[[i]] ~ 1)
      , lambda = seq(-2, 2, by = 0.1)
      , plot = F
    ) |>
    c(list(value = num_data[[i]]))
}

rm(i)

bc_trans=
  bc_trans |>
  lapply(
    \(x)
    list(
      rep(NA, length(x$value))
       ,(x$value^(x$x[which.max(x$y)]) - 1) / x$x[which.max(x$y)]
    )[[ifelse(abs(x$x[which.max(x$y)]) < 1e-10, 1, 2)
    ]]
  ) |>
  imap(
    ~ data.frame(trans=.x) |>
      `colnames<-`(.y)
  )

bc_trans <-
  bc_trans[sapply(bc_trans, \(x) !all(is.na(x[[1]])))]
```

```{r Normality test of transformed numerical variables, include=FALSE}
normal_test_after_trans <-
  simple_trans |>
  c(list(bct = bc_trans)) |>
  imap(
    ~ .x |>
      lapply(
        \(x)
        suppressWarnings(
            ks.test(
              x[[1]]
              , y = "pnorm"
              , mean = mean(x[[1]], na.rm = TRUE)
              , sd = sd(x[[1]], na.rm = TRUE)
            )
          )
      ) |>
      lapply(tidy) |>
      imap(~ mutate(.x, variable = .y)) |>
      reduce(rbind) |>
      mutate(func = .y)
  ) |>
  reduce(rbind) |>
  select(func, variable, p.value) |>
  mutate_at("func", \(x) factor(x, unique(x))) |>
  group_by(variable) |>
  mutate(best_trans = func[which.max(p.value)]) |>
  ungroup() |>
  spread(func, p.value) |>
  right_join(
    data.frame(variable = var_num_non_normal)
    , by = join_by(variable)
  ) |>
  mutate(
    p.value=
      ifelse(
        best_trans == "log"
        , log
        , ifelse(
          best_trans == "sqrt"
          , sqrt
          , ifelse(
            best_trans == "inv"
            , inv
            , ifelse(
              best_trans == "log2"
              , log2
              , ifelse(
                best_trans == "exp"
                , exp
                , ifelse(
                  best_trans == "asinh"
                  , asinh
                  , bct
                )
              )
            )
          )
        )
      )
  ) |>
  select(variable, best_trans, p.value, everything())
```

```{r table-9, echo=FALSE}
normal_test_after_trans |>
  mutate(variable = paste0(variable, ifelse(p.value <= 0.05, "*", ""))) |>
  arrange(p.value) |>
  mutate_if(is.numeric, \(x) ifelse(x < 0.001, "<0.001", round(x, 3))) |>
  mutate_if(is.numeric, as.character) |>
  kable(
    caption = "Table 9. Normality test after transformation."
    , format = kable_format
  ) |>
  footnote("*, p-value <=0.05, Shapiro-Wilk normality test.") |>
  kable_classic() |>
  column_spec(1:10, extra_css = "vertical-align:top;")
```

```{r Determine num vars that are not normal after transformed, include=FALSE}
var_num_non_normal_after_trans <-
  normal_test_after_trans |>
  filter(p.value <= 0.05) |>
  pull(variable)
```

```{r Numerical variables that are not normal after transformation, echo=FALSE}
var_num_non_normal_after_trans |>
  paste0(collapse = ", ") |>
  cat()
```

```{r Finalize transformed data, include=FALSE}
transformed_data <-
  num_data |>
  cbind(cat_data) |>
  select_at(colnames(infer_data))
```

# Outlier analysis

```{r Determine exception for outlier analysis, include=FALSE}
trans_ps_num_exception <-
  c("t"
    ,"maternal_age"
    , "gravida"
    , "bbw_g"
    , "ga_wk"
    , "as1"
    , "as5"
    , "resuscitation_at_birth"
    , "steroid_antenatal"
    , "surfactant"
    , "bbw_z"
    , "bhc_z"
    , "death_age"
    , "resp_supp_agg_cum_day_qw"
    , "fio2_cum_day_qw"
    , "fio2_cum_level_qw"
    , "resp_supp_agg_cum_day_pct"
    , "fio2_cum_day_pct"
    , "fio2_cum_level_pct"
    , "steroid_postnatal"
    , "fio2_raw"
    , "inotropic"
    , "blood_volume"
    , "transfusion"
    , "blood_culture"
    , "plt"
    , "wbc"
    , "feeding"
    , "nec"
    , "aki"
  )
```

```{r Numerical var after transformation, include=FALSE}
trans_ps_num_data <-
  transformed_data |>
  select_if(sapply(transformed_data, is.numeric))

trans_ps_num_data <-
  trans_ps_num_data |>
  select_at(setdiff(colnames(trans_ps_num_data), trans_ps_num_exception))
```

```{r Relevant numerical var after transformation, echo=FALSE}
trans_ps_num_data |>
  colnames() |>
  paste0(collapse = ", ") |>
  cat()
```

# Correlation matrix

```{r Identify and create missingness variables, include=FALSE}
ms_added_data0 <-
  transformed_data |>
  select(-id) |>
  sapply(\(x) any(is.na(x))) |>
  which() |>
  names() |>
  lapply(
    \(x)
    transformed_data |>
      select_at(x) |>
      `colnames<-`("value") |>
      mutate(value = ifelse(is.na(value), "yes", "no")) |>
      `colnames<-`(paste0("ms_", x))
  ) |>
  reduce(cbind) |>
  cbind(mutate(transformed_data, t_wk = ceiling(t / 7))) |>
  select(id, t_wk, t, everything())

ms_added_data <-
  ms_added_data0 |>
  select(-id)
```

```{r Check categorical variables with a category of 1 value, include=FALSE}
var_cat_val1 <-
  ms_added_data |>
  select_if(!sapply(ms_added_data, is.numeric)) |>
  mutate_all(as.character) |>
  gather(variable, value) |>
  group_by_all() |>
  summarize(n = n(), .groups = "drop") |>
  filter(n <= 1) |>
  pull(variable) |>
  unique()
```

```{r Categorical variables with a category of 1 value, echo=FALSE}
var_cat_val1 %>%
  paste0(collapse=', ') %>%
  cat()
```

```{r Pair-wise distribution of categorical variables, include=FALSE}
pairwise_cat_sum <-
  ms_added_data |>
  select_if(
    !sapply(ms_added_data, is.numeric)
    & !colnames(ms_added_data) %in% var_cat_val1
  ) |>
  colnames() |>
  combn(2) |>
  as.data.frame() |>
  lapply(
    \(x)
    ms_added_data |>
      select_at(x) |>
      group_by_all() |>
      summarize(n = n(), .groups = "drop") |>
      select_at(c(x, "n")) |>
      `colnames<-`(c("V1_value", "V2_value", "n")) |>
      mutate(V1 = x[1], V2 = x[2])
  ) |>
  lapply(
    \(x)
    expand.grid(
      V1_value = unique(x$V1_value)
      , V2_value = unique(x$V2_value)
      ) |>
      mutate_all(as.character) |>
      left_join(x, by = join_by(V1_value, V2_value)) |>
      mutate_at("n", \(x) ifelse(is.na(x), 0, x)) |>
      fill(V1, V2)
  ) |>
  reduce(rbind) |>
  select(V1, V1_value, V2, V2_value, everything())
```

```{r Pair-wise perfect separation, include=FALSE}
pairwise_cat_sum_ps <-
  pairwise_cat_sum |>
  group_by(V1, V2) |>
  summarize(ps = any(n == 0), .groups = "drop")
```

```{r table-10, echo=FALSE}
pairwise_cat_sum |>
  inner_join(
    pairwise_cat_sum_ps |>
      filter(ps) |>
      select(-ps)
    , by = join_by(V1, V2)
  ) |>
  filter(n == 0) |>
  kable(
    caption =
      "Table 10. Categorical variables with pair-wise perfect separation."
    , format = kable_format
  ) |>
  kable_classic()
```

```{r Variable pairs for correlation tests, include=FALSE}
correlation_pair <-
  ms_added_data |>
  colnames() |>
  setdiff(var_cat_val1) |>
  combn(2) |>
  as.data.frame() |>
  t() |>
  as.data.frame() |>
  `rownames<-`(NULL) |>
  filter(str_remove_all(V1, "^ms_") != str_remove_all(V2, "^ms_")) |>
  filter(!(str_detect(V1, "resp_supp") & str_detect(V2, "resp_supp"))) |>
  filter(
    !(str_detect(V1, "fio2_cum_level") & str_detect(V2, "fio2_cum_level"))
  ) |>
  filter(
    !(str_detect(V1, "fio2_cum_day") & str_detect(V2, "fio2_cum_day"))
  ) |>
  filter(
    !((str_detect(V1, "fio2_raw") & str_detect(V2, "fio2_cum_level"))
      | (str_detect(V1, "fio2_cum_level") & str_detect(V2, "fio2_raw"))
    )
  ) |>
  filter(!(str_detect(V1, "bbw") & str_detect(V2, "bbw"))) |>
  filter(!(str_detect(V1, "bhc") & str_detect(V2, "bhc"))) |>
  filter(
    !((str_detect(V1, "qw") & str_detect(V2, "pct"))
      | (str_detect(V1, "pct") & str_detect(V2, "qw"))
    )
  ) |>
  filter(!(str_detect(V1, "^ms_plt") | str_detect(V2, "^ms_plt"))) |>
  filter(!(str_detect(V1, "^ms_wbc") | str_detect(V2, "^ms_wbc"))) |>
  filter(
    !(str_detect(V1, "^ms_death_age") | str_detect(V2, "^ms_death_age"))
  ) |>
  filter(
    !(str_detect(V1, "^ms_rop_severe") | str_detect(V2, "^ms_rop_severe"))
  ) |>
  filter(
    !(str_detect(V1, "^ms_bpd_grade") | str_detect(V2, "^ms_bpd_grade"))
  ) |>
  filter(
    !(str_detect(V1, "^ms_eugr_hc") | str_detect(V2, "^ms_eugr_hc"))
  ) |>
  filter(
    !(str_detect(V1, "^ms_eugr_bw") | str_detect(V2, "^ms_eugr_bw"))
  ) |>
  filter(
    !(str_detect(V1, "^ms_hearing") | str_detect(V2, "^ms_hearing"))
  ) |>
  filter(!(V1 %in% c("t", "t_wk") & V2 %in% c("t", "t_wk"))) |>
  mutate(V1_unit = V1, V2_unit = V2) |>
  mutate_at(
    vars(V1_unit, V2_unit)
    , \(x)
      case_when(
        str_remove_all(x, "^ms_")
        %in% unlist(
          lapply(raw_data1[str_detect(names(raw_data1), "42d$")], colnames)
        )
        | str_remove_all(x, "^ms_") == "t"
        ~ "id|t_wk|t"
        , str_remove_all(x, "^ms_")
          %in% unlist(
            lapply(raw_data1[str_detect(names(raw_data1), "6w$")], colnames)
          )
          | str_remove_all(x, "^ms_") == "t_wk"
          ~ "id|t_wk"
        , str_remove_all(x, "^ms_")
          %in% unlist(
            lapply(
              raw_data1[!str_detect(names(raw_data1), "42d$|6w$")]
              , colnames
            )
          )
          ~ "id"
      )
  ) |>
  mutate(
    unit =
      mapply(
        \(x, y)
          c(str_split(x, "\\|")[[1]], str_split(y, "\\|")[[1]]) |>
            unique() |>
            paste0(collapse = "|")
        , V1_unit
        , V2_unit
      )
  ) |>
  filter(
    !(V1 == "t" | V2 == "t")
    | (V1 == "t" & V2_unit != "id")
    | (V2 == "t" & V1_unit != "id")
  ) |>
  filter(
    !(V1 == "t_wk" | V2 == "t_wk")
    | (V1 == "t_wk" & V2_unit != "id")
    | (V2 == "t_wk" & V1_unit != "id")
  ) |>
  select(-V1_unit, -V2_unit)
```

```{r Conduct correlation tests per pair with PS, eval=FALSE, include=FALSE}
correlation_matrix_ps0 <-
  correlation_pair |>
  filter(
    paste0(V1, V2)
    %in% c(
      pairwise_cat_sum_ps |>
        filter(ps) |>
        unite(V1V2, V1, V2, sep = "") |>
        pull(V1V2)
    )
  )

correlation_matrix_ps <-
  correlation_matrix_ps0 |>
  pmap(
    \(V1, V2, unit)
    list(
      data =
        ms_added_data0[, c(V1, V2, str_split(unit, "\\|")[[1]])] |>
        unique()
      , V1 = V1
      , V2 = V2
    )
  )

if (!dir.exists("data/correlation_matrix_ps")){
  dir.create("data/correlation_matrix_ps")
}

start <- TRUE
cl <- min(6, detectCores())
source("R/parallel_computing-codes.R")

correlation_matrix_ps[
  correlation_matrix_ps |>
    sapply(
      \(x)
      !paste0(x$V1, "_", x$V2, ".rds")
      %in% list.files("data/correlation_matrix_ps")
    )
  ] |>
  pblapply(
    FUN =
      \(x, auto_stat_tests = auto_stat_tests, ms_added_data = ms_added_data)
      suppressWarnings(auto_stat_tests(
          x$data[[x$V1]]
          , x$data[[x$V2]]
          , perfect_separation = TRUE
        )) |>
        list() |>
        `names<-`("obj") |>
        c(list(V1 = x$V1, V2 = x$V2)) |>
        saveRDS(paste0("data/correlation_matrix_ps/",x$V1,"_",x$V2,".rds"))
    , auto_stat_tests = auto_stat_tests
    , ms_added_data = ms_added_data
    ,  cl = cl
  )

start <- FALSE
source("R/parallel_computing-codes.R")

correlation_matrix_ps <-
  correlation_matrix_ps0 |>
  pmap(\(V1, V2, unit) list(V1 = V1, V2 = V2)) |>
  pblapply(
    \(x)
    suppressWarnings(
      tidy(
        readRDS(
          paste0("data/correlation_matrix_ps/",x$V1,"_",x$V2,".rds")
        )$obj
      )
    ) |>
    filter(!str_detect(term, "\\(Intercept\\)")) |>
    filter(!(conf.low <= 0 & conf.high >= 0)) |>
    summarize(n_sig = n()) |>
    mutate(p.value = ifelse(n_sig > 0, 0, 1)) |>
    filter(!is.na(p.value)) |>
    select(p.value) |>
    mutate(V1 = x$V1, V2 = x$V2)
  ) |>
  reduce(rbind)

saveRDS(correlation_matrix_ps, "data/correlation_matrix_ps.rds")
```

```{r Load pre-conducted correlation tests per pair with PS, include=FALSE}
correlation_matrix_ps <- readRDS("data/correlation_matrix_ps.rds")
```

```{r Conduct correlation tests for each pair without PS, include=FALSE}
correlation_matrix_non_ps <-
  correlation_pair |>
  filter(
    !paste0(V1, V2)
    %in% c(
      pairwise_cat_sum_ps |>
        filter(ps) |>
        unite(V1V2, V1, V2, sep = "") |>
        pull(V1V2)
    )
  ) |>
  pmap(
    \(V1, V2, unit)
    list(
      data =
        ms_added_data0[, c(V1, V2, str_split(unit, "\\|")[[1]])]
      , V1 = V1
      , V2 = V2
    )
  ) |>
  lapply(
    \(x)
    list(
      obj =
        try(
          suppressWarnings(auto_stat_tests(
              x$data[[x$V1]]
              ,x$data[[x$V2]]
              ,normal_V1 = !x$V1 %in% var_num_non_normal_after_trans
              ,normal_V2 = !x$V2 %in% var_num_non_normal_after_trans
            ))
        )
      , V1 = x$V1
      ,V2 = x$V2
    )
  )


correlation_matrix_non_ps_succeed <-
  correlation_matrix_non_ps[
    sapply(
      correlation_matrix_non_ps
      , \(x) paste0(class(x$obj), collapse = " ") != "try-error"
    )
  ] |>
  lapply(
    \(x)
    x$obj |>
      tidy() |>
      filter(!is.na(p.value)) |>
      select(p.value) |>
      mutate(
        V1 = x$V1
        ,V2 = x$V2
      )
  ) |>
  reduce(rbind)

correlation_matrix_non_ps_failed <-
  correlation_pair |>
  filter(
    !paste0(V1, V2)
    %in% c(
      pairwise_cat_sum_ps |>
        filter(ps) |>
        unite(V1V2, V1, V2, sep = "") |>
        pull(V1V2)
    )
  ) |>
  slice(
    which(
      sapply(
        correlation_matrix_non_ps
        , \(x) paste0(class(x$obj), collapse = " ") == "try-error"
      )
    )
  ) |>
  mutate(p.value = as.numeric(NA)) |>
  select(p.value, V1, V2)

correlation_matrix_non_ps <-
  correlation_matrix_non_ps_succeed |>
  rbind(correlation_matrix_non_ps_failed)
```

```{r Conduct correlation tests for each pair, include=FALSE}
correlation_matrix <-
  correlation_matrix_ps |>
  rbind(correlation_matrix_non_ps) |>
  mutate(p.value = p.adjust(p.value, "BH")) |>
  rename(cor.p.value = p.value) |>
  right_join(
    ms_added_data |>
      colnames() |>
      combn(2) |>
      as.data.frame() |>
      t() |>
      as.data.frame() |>
      `rownames<-`(NULL)
    ,by = join_by(V1, V2)
  ) |>
  mutate(
    V1 = factor(V1, colnames(ms_added_data))
    ,V2 = factor(V2, levels(V1))
  ) |>
  arrange(V1, V2)
```

```{r Plot correlation matrix, include=FALSE}
same_v_corr_df =
  data.frame(
    cor.p.value = 0
    ,V1 = colnames(ms_added_data)
    ,V2 = colnames(ms_added_data)
    ,sig = "2 - Significant"
  )

correlation_matrix_plot <-
  correlation_matrix |>
  mutate(
    V1 = factor(V1, rev(levels(V1)))
    ,sig =
      ifelse(
        is.na(cor.p.value)
        ,ifelse(
          str_remove_all(V1, "^ms_") == str_remove_all(V2, "^ms_")
          ,"3 - Not tested†"
          ,ifelse(
            V1 %in% var_cat_val1
            | V2 %in% var_cat_val1
            ,"4 - Not tested‡"
            ,"5 - Not tested§"
          )
        )
        ,ifelse(cor.p.value <= 0.05, "2 - Significant", "1 - Not significant")
      ) |>
      factor()
    ,sig = factor(sig)
    ,cor.p.value = ifelse(cor.p.value<0.001, "<0.001", round(cor.p.value,3))
  ) |>
  rbind(same_v_corr_df) |>
  ggplot(aes(V1, V2, fill = sig)) +
  geom_tile(color = "white", na.rm = TRUE) +
  # geom_text(aes(label = cor.p.value), size = 2.5, na.rm = TRUE) +
  geom_tile(data = same_v_corr_df, fill = "white") +
  geom_text(
    data =
      same_v_corr_df |>
      mutate(label = V1)
    ,aes(label = label)
    ,size = 1.5
    ,angle = 45
    ,hjust = 1
    ,nudge_x = 0.15
    ,nudge_y = 0.15
  ) +
  coord_flip() +
  scale_x_discrete(expand = expansion(add = 10)) +
  scale_y_discrete(expand = expansion(add = 5)) +
  xlab("") +
  ylab("") +
  scale_fill_discrete("Significance*") +
  theme(
    panel.grid = element_blank()
    ,panel.border = element_blank()
    ,axis.ticks = element_blank()
    ,axis.text = element_blank()
  )
```

```{r figure-3, echo=FALSE, fig.height=5, fig.width=7}
correlation_matrix_plot
```

```{r Write pairs with significant correlations, eval=FALSE, include=FALSE}
correlation_matrix |>
  filter(cor.p.value <= 0.05) |>
  filter(
    !(V1 %in% paste0(var_num_non_normal, "_trans")
      | V2 %in% paste0(var_num_non_normal, "_trans")
    )
  ) |>
  select(V1, V2) |>
  write_csv("inst/extdata/correlation.csv")
```

# Missing value imputation

```{r Imputation predictor matrix, include=FALSE}
imp_predictor_matrix <-
  correlation_matrix |>
  filter(!is.na(cor.p.value)) |>
  mutate(imp_predictor = ifelse(cor.p.value <= 0.05, 1, 0)) |>
  select(V1, V2, imp_predictor) |>
  mutate_at(c("V1", "V2"), str_remove_all, "^ms_") |>
  unique() |>
  right_join(
    expand.grid(
      V1 = colnames(transformed_data)
      ,V2 = colnames(transformed_data)
      ,stringsAsFactors = FALSE
    )
    ,by = join_by(V1, V2)
  ) |>
  mutate(imp_predictor = ifelse(V1 == V2, 0, imp_predictor)) |>
  pmap(
    \(V1, V2, imp_predictor)
    data.frame(
      V1_V2 =
        sort(c(V1, V2)) |>
        paste0(collapse = "|")
      ,imp_predictor = imp_predictor
    )
  ) |>
  reduce(rbind) |>
  separate(V1_V2, c("V1", "V2"), sep = "\\|") |>
  group_by(V1, V2) |>
  summarize(
    imp_predictor = as.integer(sum(imp_predictor, na.rm = TRUE) > 0)
    ,.groups = "drop"
  ) |>
  spread(V2, imp_predictor, fill = 0) |>
  column_to_rownames(var = "V1") |>
  as.matrix()

imp_predictor_matrix <-
  imp_predictor_matrix[
    colnames(transformed_data)
    ,colnames(transformed_data)
  ]
```

```{r Performing multiple imputation, eval=FALSE, include=FALSE}
imp_results <-
  suppressWarnings(
    mice(
      data = transformed_data
      ,method = 'pmm'
      ,m = 10
      ,seed = seed
      ,predictorMatrix = imp_predictor_matrix
      ,print = FALSE
    )
  )

saveRDS(imp_results, "data/imp_results.rds")
```

```{r Load pre-performed multiple imputation, include=FALSE}
imp_results <- readRDS("data/imp_results.rds")
```

```{r Obtain imputed data, include=FALSE}
imputed_data <- complete(imp_results, 1)

imputed_data <-
  imputed_data |>
  imap(
    ~ list(
        select_at(transformed_data, .y)
        ,select_at(imputed_data, .y)
      )[[ifelse(.y %in% colnames(raw_data1$outcomes), 1, 2)]]
  ) |>
  reduce(cbind)
```














































